- name: "Configure kernel for ElasticSearch"
  hosts: nodes

  tasks:
  - name: Create file to tune ES for kernel
    copy:
      dest: /etc/sysctl.d/99-elasticsearch.conf
      content: |
        vm.max_map_count = 262144
        }

  - name: Apply ES tuning to kernel
    sysctl:
      name: vm.max_map_count
      value: 262144
      state: present

- name: "Install Istio operator"
  hosts: masters[0]

  tasks:
  - name: Check if istio-operator namespace exists
    command: >-
      oc get namespace istio-operator
    register: get_istio_operator_namespace
    changed_when: false
    failed_when: false

  - name: Create istio-operator namespace
    shell: >-
      oc new-project istio-operator
    when: get_istio_operator_namespace.rc != 0

  - name: Verify servicemesh-operator objects exist
    command: >-
      oc get crd installations.istio.openshift.com -n istio-operator -o json
    changed_when: false
    failed_when: false
    register: verify_istio_crd

  - name: Copy servicemesh-operator template
    copy:
      src: "files/servicemesh-operator.yaml"
      dest: /tmp/servicemesh-operator.yaml
    when: verify_istio_crd.rc != 0

  - name: Create servicemesh-operator template
    shell: >-
      oc apply -n istio-operator -f /tmp/servicemesh-operator.yaml
    failed_when: false
    when: verify_istio_crd.rc != 0

  - name: Check if istio-system namespace exists
    command: >-
      oc get project istio-system
    register: get_istio_system_namespace
    changed_when: false
    failed_when: false

  - name: Create istio-operator namespace
    shell: >-
      oc new-project istio-system
    when: get_istio_system_namespace.rc != 0

  - name: Copy istio-installation CRD
    copy:
      src: "files/istio-installation.yaml"
      dest: /tmp/istio-installation.yaml

  - name: Check if basic-install controlplane CRD exists
    command: >-
      oc get controlplanes basic-install
    register: get_controlplane_crd
    changed_when: false
    failed_when: false

  - name: Create istio-installation CRD
    shell: >-
      oc create -f /tmp/istio-installation.yaml -n istio-system
    when: get_controlplane_crd.rc != 0
