- name: "Clean up Service Mesh resources"
  hosts: masters[0]

  tasks:
  - name: Check if istio-system namespace exists
    command: >-
      oc get namespace istio-system
    register: get_istio_system_namespace
    changed_when: false
    failed_when: false

  - name: Clean up objects and delete istio-system namespace
    command: >-
      oc delete namespace istio-system
    when: get_istio_system_namespace.rc == 0

  - name: Check if istio-operator namespace exists
    command: >-
      oc get namespace istio-operator
    register: get_istio_operator_namespace
    changed_when: false
    failed_when: false

  - name: Clean up objects and delete istio-operator namespace
    command: >-
      oc delete namespace istio-operator
    when: get_istio_operator_namespace.rc == 0

  - name: Get CRDs that match Service Mesh labels
    command: >-
      oc get crd -l 'app in (istio-operator-job, kiali, istio-citadel, istio-pilot, mixer, istio-mixer)'
    register: get_service_mesh_crd
    changed_when: false
    failed_when: false

  - name: Delete CRDs that match Service Mesh labels
    command: >-
      oc delete crd -l 'app in (istio-operator-job, kiali, istio-citadel, istio-pilot, mixer, istio-mixer)'
    when: get_service_mesh_crd.rc == 0 and get_service_mesh_crd.stdout != ""

  - name: Check if ClusterRoleBinding for Service Mesh exists
    command: >-
      oc get clusterrolebinding istio-authenticated
    register: get_cluster_role_binding
    changed_when: false
    failed_when: false

  - name: Delete ClusterRoleBinding for Service Mesh
    command: >-
      oc delete clusterrolebinding istio-authenticated    
    when: get_cluster_role_binding.rc == 0 and get_cluster_role_binding.stdout != ""

  - name: Check if ClusterRole for Service Mesh exists
    command: >-
      oc get clusterrole istio-authenticated
    register: get_cluster_role
    changed_when: false
    failed_when: false

  - name: Delete ClusterRole for Service Mesh
    command: >-
      oc delete clusterrole istio-authenticated    
    when: get_cluster_role.rc == 0 and get_cluster_role.stdout != ""

